
// Code generated by a template
using TmTFramework.Core.DataAccess;
using TmTFramework.Entities.Concrete;

namespace TmTFramework.DataAccess.Abstract
{

   
   
    public interface IArizaKategoriDal:IEntityRepository<ArizaKategori>
    {
       
    }

}
