
// Code generated by a template
using System.Collections.Generic;
using TmTFramework.Core.DataAccess;
using TmTFramework.Entities.ComplexType;
using TmTFramework.Entities.Concrete;

namespace TmTFramework.DataAccess.Abstract
{

   
   
    public interface IMusteriDal:IEntityRepository<Musteri>
    {

        List<MusteriIndexList> GetMusteriIndexList();
    }

}
