
// Code generated by a template

using System;
using System.Collections.Generic;
using TmTFramework.Core.DataAccess;
using TmTFramework.Entities.ComplexType;
using TmTFramework.Entities.Concrete;

namespace TmTFramework.DataAccess.Abstract
{
    public interface IServisDal:IEntityRepository<Servis>
    {
        List<ServisDetails> GetServisDetails();

        ServisDetails GetServisDetailsById(Guid id);
    }

}
