
// Code generated by a template
using TmTFramework.Core.DataAccess.EntityFramework;
using TmTFramework.DataAccess.Abstract;
using TmTFramework.Entities.Concrete;
using System.Linq;
using System.Collections.Generic;
using System.Data.Entity;
using TmTFramework.Entities.ComplexType;
using System;
using System.Data.Entity.Core.Common.CommandTrees;


namespace TmTFramework.DataAccess.Concrete.EntityFramework
{


    
    public class EfAracDal : EfEntityRepositoryBase<Arac, TMTServisContext>, IAracDal
    {
        public List<AracDetay> GetAllWithDetail()
        {
            using (TMTServisContext context = new TMTServisContext())
            {
                var result =
                    (from a in context.Arac
                    join m in context.Musteri on a.MusteriId equals m.Id
                    select new AracDetay()
                    {
                        Id = a.Id,
                        Marka = a.Marka,
                        Model = a.Model,
                        MusteriAdi = m.AdSoyad,
                        Yil = a.Yýl.ToString(),
                        Plaka = a.Plaka,
                        ServisAdet = context.Servis.Count(h=>h.AracId==a.Id)

                    }).ToList();



                return result;
            }
        }

        public AracKayitBilgi GetCarInfoForAd(Guid id)
        {
            using (TMTServisContext context = new TMTServisContext())
            {


                var result =
                    from s in context.Arac
                    join m in context.Musteri on s.MusteriId equals m.Id
                    where s.Id == id
                    select new AracKayitBilgi()
                    {
                        Marka = s.Marka,
                        Model = s.Model,
                        MusteriAdi = m.AdSoyad,
                        Yil = s.Yýl.ToString(),
                        Plaka = s.Plaka

                    };



                return result.FirstOrDefault();
            }
        }
    }

}
