
// Code generated by a template
using System.Collections.Generic;
using TmTFramework.Core.DataAccess.EntityFramework;
using TmTFramework.DataAccess.Abstract;
using TmTFramework.Entities.ComplexType;
using TmTFramework.Entities.Concrete;
using System.Linq;
using System.Collections.Generic;
using System.Data.Entity;

namespace TmTFramework.DataAccess.Concrete.EntityFramework
{


    //public class EfBolumDal : EfEntityRepositoryBase<Bolum, TMTServisContext>,IBolumDal
    public class EfMusteriDal : EfEntityRepositoryBase<Musteri, TMTServisContext>, IMusteriDal
    {
        public List<MusteriIndexList> GetMusteriIndexList()
        {
            using (TMTServisContext context = new TMTServisContext())
            {

               return (from m in context.Musteri
                              select new MusteriIndexList
                              {
                                  Musterisi = m,
                                  AracAdedi = context.Arac.Where(h => h.MusteriId == m.Id).Count()
                              }).ToList();
            }
        }
    }

}
