
// Code generated by a template
using TmTFramework.Core.DataAccess.EntityFramework;
using TmTFramework.DataAccess.Abstract;
using TmTFramework.Entities.Concrete;

namespace TmTFramework.DataAccess.Concrete.EntityFramework
{

   
   //public class EfBolumDal : EfEntityRepositoryBase<Bolum, TMTServisContext>,IBolumDal
   public class EfPersonelDal : EfEntityRepositoryBase<Personel,TMTServisContext >,IPersonelDal
    {
        
    }

}
