
// Code generated by Hüsrev YILDIZ
using System;
using TmTFramework.Core.Entities;

namespace TmTFramework.Entities.Concrete
{



    //AracArizaKayit
    public class Arac : IEntity
    {
        public Guid Id { get; set; }
        public Guid MusteriId { get; set; }
        public string Plaka { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public int? Yıl { get; set; }
    }

}
