
// Code generated by Hüsrev YILDIZ
using System;
using TmTFramework.Core.Entities;

namespace TmTFramework.Entities.Concrete
{



    //AracArizaKayit
    public class AracArizaKayit : IEntity
    {
        public Guid Id { get; set; }
        public Guid ArizaKategoriId { get; set; }
        public string Aciklama { get; set; }
        public DateTime? BaslamaTarihi { get; set; }
        public int? TahminiSure { get; set; }
        public DateTime? KayitZamani { get; set; }
        public Guid? PersonelId { get; set; }
        public Guid? ServisId { get; set; }
        public bool ArizaTamamlandiMi { get; set; }
    }

}
