
// Code generated by Hüsrev YILDIZ
using System;
using TmTFramework.Core.Entities;

namespace TmTFramework.Entities.Concrete
{



    //AracArizaKayit
    public class ArizaKategori : IEntity
    {
        public Guid Id { get; set; }
        public string Adi { get; set; }
        public Guid? UstArizaKategoriId { get; set; }
        public string Aciklama { get; set; }
    }

}
