
// Code generated by Hüsrev YILDIZ
using System;
using System.ComponentModel.DataAnnotations;
using TmTFramework.Core.Entities;

namespace TmTFramework.Entities.Concrete
{



    //AracArizaKayit
    public class Musteri : IEntity
    {
        [Key]
        public Guid Id { get; set; }
        public string AdSoyad { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public string Email { get; set; }
    }

}
