
// Code generated by Hüsrev YILDIZ
using System;
using TmTFramework.Core.Entities;

namespace TmTFramework.Entities.Concrete
{



    //AracArizaKayit
    public class Personel : IEntity
    {
        public Guid Id { get; set; }
        public string AdSoyad { get; set; }
        public string Tc { get; set; }
        public string Telefon { get; set; }
        public string Unvan { get; set; }
        public string Adres { get; set; }
    }

}
