
// Code generated by Hüsrev YILDIZ
using System;
using TmTFramework.Core.Entities;

namespace TmTFramework.Entities.Concrete
{

     

	 //Role
      public class Role:IEntity
      {
	                         public Guid 	Id{ get; set; } 
					                          public string 	Name{ get; set; } 
					         }

}
