
// Code generated by Hüsrev YILDIZ
using System;
using TmTFramework.Core.Entities;

namespace TmTFramework.Entities.Concrete
{



    //AracArizaKayit
    public class Servis : IEntity
    {
        public Guid Id { get; set; }
        public Guid AracId { get; set; }
        public DateTime ServisZamani { get; set; }
    }

}
