
// Code generated by Hüsrev YILDIZ
using System;
using TmTFramework.Core.Entities;

namespace TmTFramework.Entities.Concrete
{



    //AracArizaKayit
    public class Urun : IEntity
    {
        public Guid Id { get; set; }
        public string Marka { get; set; }
        public string Kod { get; set; }
        public string Aciklama { get; set; }
        public string RafKodu { get; set; }
    }

}
