
// Code generated by Hüsrev YILDIZ
using System;
using TmTFramework.Core.Entities;

namespace TmTFramework.Entities.Concrete
{

     

	 //Role
      public class UserRole:IEntity
      {
	                         public Guid 	Id{ get; set; } 
					                          public Guid 	RoleId{ get; set; } 
					                          public Guid 	UserId{ get; set; } 
					         }

}
