
// Code generated by Hüsrev YILDIZ
using System;
using TmTFramework.Core.Entities;

namespace TmTFramework.Entities.Concrete
{

     

	 //Role
      public class User:IEntity
      {
	                         public Guid 	Id{ get; set; } 
					                          public string 	UserName{ get; set; } 
					                          public string 	Password{ get; set; } 
					                          public string 	FirsName{ get; set; } 
					                          public string 	LastName{ get; set; } 
					                          public string 	Email{ get; set; } 
					         }

}
