
// Code generated by a template
using System.Collections.Generic;
using TmTFramework.Core.DataAccess.Dapper;
using TmTFramework.DataAccess.Abstract;
using TmTFramework.Entities.ComplexType;
using TmTFramework.Entities.Concrete;
using System.Linq;
using System.Collections.Generic;
using System.Data.Entity;

namespace TmTFramework.DataAccess.Concrete.Dapper
{


    //public class EfBolumDal : EfEntityRepositoryBase<Bolum, TMTServisContext>,IBolumDal
    public class DapperMusteriDal : DapperRepositoryBase<Musteri>, IMusteriDal
    {
        private DapperHelper<Musteri> _dapperHelper;
        public DapperMusteriDal(DapperHelper<Musteri> dapperHelper) : base(dapperHelper)
        {
            _dapperHelper = dapperHelper;
        }

        public List<MusteriIndexList> GetMusteriIndexList()
        {

            var result =  _dapperHelper.QueryCommand(
                System.Data.CommandType.Text,
                $@"select * ,
                    (select count(*) from Arac a where a.MusteriId = m.Id) as AracAdedi
               from Musteri m", null);

            List<MusteriIndexList> list = new List<MusteriIndexList>();

            foreach (var item in result)
            {
                list.Add(
                    new MusteriIndexList()
                    {
                        Musterisi = new Musteri
                        {
                            Adres = item.Adres,
                            AdSoyad = item.AdSoyad,
                            Email = item.Email,
                            Id=item.Id,
                            Telefon =item.Telefon,
                            VergiDairesi =item.VergiDairesi,
                            VergiNo =item.VergiNo,
                        },
                        AracAdedi = item.AracAdedi
                    });
            }

            return list;
        }
    }

}
