
// Code generated by a template
using System;
using System.Collections.Generic;
using TmTFramework.Entities.Concrete;

namespace TmTFramework.Business.Abstract
{



    public interface IAracArizaKayitService
    {
        List<AracArizaKayit> GetAll();
        List<AracArizaKayit> GetListByServisId(Guid id);
        AracArizaKayit GetById(Guid id);

        AracArizaKayit Add(AracArizaKayit aracarizakayit);
        List<AracArizaKayit> AddRange(List<AracArizaKayit> aracArizaKayitlari);

        AracArizaKayit Update(AracArizaKayit aracarizakayit);

        void Delete(AracArizaKayit aracarizakayit);
        void DeleteRange(List<AracArizaKayit> arac);
    }

}
