
// Code generated by a template
using System;
using System.Collections.Generic;
using TmTFramework.Entities.ComplexType;
using TmTFramework.Entities.Concrete;

namespace TmTFramework.Business.Abstract
{

    public interface IAracService
    {
        List<Arac> GetAll();

        Arac GetById(Guid id);

        Arac Add(Arac arac);

        Arac Update(Arac arac);
        
		void Delete(Arac arac);

        

        /// <summary>
        /// Ariza Kaydý yapabilmek için Gerekli olan Araç bilgileerini getirir
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        AracKayitBilgi GetCarInfoForAd(Guid id);

        List<AracDetay> GetAllWithDetail();

    }

}
