
// Code generated by a template
using System;
using System.Collections.Generic;
using TmTFramework.Entities.Concrete;

namespace TmTFramework.Business.Abstract
{

   

    public interface IArizaKategoriService
    {
        List<ArizaKategori> GetAll();

        ArizaKategori GetById(Guid id);

        ArizaKategori Add(ArizaKategori arizakategori);

        ArizaKategori Update(ArizaKategori arizakategori);
        
		void Delete(ArizaKategori arizakategori);
	}

}
