
// Code generated by a template
using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using TmTFramework.Entities.ComplexType;
using TmTFramework.Entities.Concrete;

namespace TmTFramework.Business.Abstract
{

    public interface IMusteriService
    {
        List<Musteri> GetAll();

        Musteri GetById(Guid id);

        Musteri Add(Musteri musteri);

        Musteri Update(Musteri musteri);
        
		void Delete(Musteri musteri);

        List<MusteriIndexList> GetMusteriIndexList();

        List<Musteri> GetList(Expression<Func<Musteri, bool>> filter = null);
    }

}
