
// Code generated by a template
using System;
using System.Collections.Generic;
using TmTFramework.Entities.Concrete;

namespace TmTFramework.Business.Abstract
{

   

    public interface IPersonelService
    {
        List<Personel> GetAll();

        Personel GetById(Guid id);

        Personel Add(Personel personel);

        Personel Update(Personel personel);
        
		void Delete(Personel personel);
	}

}
