
// Code generated by a template
using System;
using System.Collections.Generic;
using TmTFramework.Entities.Concrete;

namespace TmTFramework.Business.Abstract
{

   

    public interface IUrunService
    {
        List<Urun> GetAll();

        Urun GetById(Guid id);

        Urun Add(Urun urun);

        Urun Update(Urun urun);
        
		void Delete(Urun urun);
	}

}
