
// Code generated by a template
using System;
using System.Collections.Generic;
using TmTFramework.Entities.Concrete;

namespace TmTFramework.Business.Abstract
{

   

    public interface IUserRoleService
    {
        List<UserRole> GetAll();

        UserRole GetById(Guid id);

        UserRole Add(UserRole userrole);

        UserRole Update(UserRole userrole);
        
		void Delete(UserRole userrole);
	}

}
