
// Code generated by a template
using System;
using System.Collections.Generic;
using TmTFramework.Entities.Concrete;

namespace TmTFramework.Business.Abstract
{

   

    public interface IUsersService
    {
        List<User> GetAll();

        User GetById(Guid id);

        User Add(User users);

        User Update(User users);
        
		void Delete(User users);

        /// <summary>
        /// Kullanýcý adý ve þifre ile kullanýcý sorgusu yapar ve kullanýcý var ise kullanýcýyý döndürür.
        /// </summary>
        /// <param name="userName"></param>
        /// <param name="password"></param>
        /// <returns></returns>
        User GetByUserNameAndPassword(string userName, string password);

        /// <summary>
        /// Kullanýcýnýn Rollerini döndürür
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        string[] GetUserRoles(User user);

    }

}
