
// Code generated by a template Hüsrev YILDIZ
//using TmTFramework.Core.Aspects.Postsharp.ChacheAspects;
//using TmTFramework.Core.Aspects.Postsharp.ValidationAspects;
//using TmTFramework.Core.CrossCuttingConcerns.Cashing.Microsoft;
//using TmTFramework.Business.ValidationRules.FluentValidation;
using TmTFramework.Business.Abstract;
using TmTFramework.Entities.Concrete;
using System.Collections.Generic;
using System;
using TmTFramework.Core.Aspects.Postsharp.AuthoritationAspects;
using TmTFramework.DataAccess.Abstract;

namespace TmTFramework.Business.Concrete.Managers
{
    [SecuredOperation]
    public class ArizaKategoriManager:IArizaKategoriService
    {
       private IArizaKategoriDal _arizakategoriDal;

       public ArizaKategoriManager(IArizaKategoriDal arizakategoriDal)
       {
           _arizakategoriDal = arizakategoriDal;
       }

       //[CacheAspect(typeof(MemoryCacheManager),120)]
       public List<ArizaKategori> GetAll()
       {
           return _arizakategoriDal.GetList();
       }

       public ArizaKategori GetById(Guid id)
       {
           return _arizakategoriDal.Get(h => h.Id == id);
       }



       //[FluentValidationAspect(typeof(Microsoft.VisualStudio.TextTemplating8419A0B83E38449666535B438C8B65A520BAABB17F52B9D39F3CBF25BABBEEA00902FAE3481D6B0E3EF3F101D2A87BED58B273A73F08F8254A58C876398A7C04.GeneratedTextTransformation+DatabaseTableValidatior))]
       //[CacheRemoAspect(typeof(MemoryCacheManager))]
       public ArizaKategori Add(ArizaKategori arizakategori)
       {
            //ValidatorTool.FluentValidate( new Microsoft.VisualStudio.TextTemplating8419A0B83E38449666535B438C8B65A520BAABB17F52B9D39F3CBF25BABBEEA00902FAE3481D6B0E3EF3F101D2A87BED58B273A73F08F8254A58C876398A7C04.GeneratedTextTransformation+DatabaseTableValidatior(), ArizaKategori);
           return _arizakategoriDal.Add(arizakategori);
       }

        //[FluentValidationAspect(typeof(ArizaKategoriValidatior))]
        public ArizaKategori Update(ArizaKategori arizakategori)
        {
            //ValidatorTool.FluentValidate(new Microsoft.VisualStudio.TextTemplating8419A0B83E38449666535B438C8B65A520BAABB17F52B9D39F3CBF25BABBEEA00902FAE3481D6B0E3EF3F101D2A87BED58B273A73F08F8254A58C876398A7C04.GeneratedTextTransformation+DatabaseTableValidatior(), ArizaKategori);
            return _arizakategoriDal.Update(arizakategori);
        }

		 public void Delete(ArizaKategori arizakategori)
        {
            _arizakategoriDal.Delete(arizakategori);
        }
    }

}
