
// Code generated by a template Hüsrev YILDIZ
//using TmTFramework.Core.Aspects.Postsharp.ChacheAspects;
//using TmTFramework.Core.Aspects.Postsharp.ValidationAspects;
//using TmTFramework.Core.CrossCuttingConcerns.Cashing.Microsoft;
//using TmTFramework.Business.ValidationRules.FluentValidation;
using TmTFramework.Business.Abstract;
using TmTFramework.DataAccess.Abstract;
using TmTFramework.Entities.Concrete;
using System.Collections.Generic;
using System;
using TmTFramework.Core.Aspects.Postsharp.AuthoritationAspects;
using TmTFramework.Entities.ComplexType;
using System.Linq.Expressions;

namespace TmTFramework.Business.Concrete.Managers
{


    //[SecuredOperation]
    public class MusteriManager:IMusteriService
    {
       private IMusteriDal _musteriDal;

       public MusteriManager(IMusteriDal musteriDal)
       {
           _musteriDal = musteriDal;
       }

       //[CacheAspect(typeof(MemoryCacheManager),120)]
       public List<Musteri> GetAll()
       {
           return _musteriDal.GetList();
       }

       public Musteri GetById(Guid id)
       {
           return _musteriDal.Get(h => h.Id == id);
       }


       //[FluentValidationAspect(typeof(Microsoft.VisualStudio.TextTemplating8419A0B83E38449666535B438C8B65A520BAABB17F52B9D39F3CBF25BABBEEA00902FAE3481D6B0E3EF3F101D2A87BED58B273A73F08F8254A58C876398A7C04.GeneratedTextTransformation+DatabaseTableValidatior))]
       //[CacheRemoAspect(typeof(MemoryCacheManager))]
       public Musteri Add(Musteri musteri)
       {
            //ValidatorTool.FluentValidate( new Microsoft.VisualStudio.TextTemplating8419A0B83E38449666535B438C8B65A520BAABB17F52B9D39F3CBF25BABBEEA00902FAE3481D6B0E3EF3F101D2A87BED58B273A73F08F8254A58C876398A7C04.GeneratedTextTransformation+DatabaseTableValidatior(), Musteri);
           return _musteriDal.Add(musteri);
       }

        //[FluentValidationAspect(typeof(MusteriValidatior))]
        public Musteri Update(Musteri musteri)
        {
            //ValidatorTool.FluentValidate(new Microsoft.VisualStudio.TextTemplating8419A0B83E38449666535B438C8B65A520BAABB17F52B9D39F3CBF25BABBEEA00902FAE3481D6B0E3EF3F101D2A87BED58B273A73F08F8254A58C876398A7C04.GeneratedTextTransformation+DatabaseTableValidatior(), Musteri);
            return _musteriDal.Update(musteri);
        }

		 public void Delete(Musteri musteri)
        {
            _musteriDal.Delete(musteri);
        }

        public List<MusteriIndexList> GetMusteriIndexList()
        {
            return _musteriDal.GetMusteriIndexList();
        }

        public List<Musteri> GetList(Expression<Func<Musteri, bool>> filter = null)
        {
            return _musteriDal.GetList(filter);
        }
    }

}
